[package]
name = "mcf"
version = "0.1.0"
authors = ["johnrieth <john.rieth@outlook.com>"]
description = "Computational and mathematical finance"
keywords = ["mathematics", "finance", "economics", ]
categories = ["science"]

[dependencies]
